# Generated by Django 5.1.6 on 2025-02-08 17:13

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of place')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Indicate a point on the map', srid=4326, verbose_name='Geo-coordinates')),
                ('rating', models.PositiveSmallIntegerField(help_text='From 0 to 25', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Time of readings')),
                ('temperature', models.FloatField(verbose_name='Temperature (°C)')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Humidity (%)')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='Atmospheric pressure (mmHg)')),
                ('wind_direction', models.CharField(max_length=50, verbose_name='Wind direction')),
                ('wind_speed', models.FloatField(verbose_name='Wind speed (m/s)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_summaries', to='places.place')),
            ],
            options={
                'verbose_name': 'Weather Summary',
                'verbose_name_plural': 'Weather Summary',
                'ordering': ('-timestamp',),
            },
        ),
    ]
